Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - '**/version.rb'

Style/FileName:
  Exclude:
    - 'lib/lita-watson-irc.rb'
    - 'lib/lita-watson_irc.rb'

inherit_from: .rubocop_todo.yml
